# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18cd0f7802accbcbd5f1bdb7b8c2edcb8040b98b867879f6bc3f86aa481f91e844c84947888f718024b424b323d84c9a4ad3ada27320a5f15ed4f7408f5fcb4f

test:
  secret_key_base: 7029fc2aab80a198daab29df255ce84ed18c33c5935b74490e641e4358a8ec921365c35d7b359685f0d7c6059370a4d22aafd22cae8f6a8ca1843624c023ad2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
